import {articles,customers} from './data.js';
import {respondTechnical} from './technical.js';
const words=s=>(s.toLowerCase().match(/[a-z]{3,}/g)||[]).filter(w=>!['what','with','this','that','your','have','from','would','about','please','there','order'].includes(w));
export function lookupOrder(input){const match=input.match(/NS[- ]?(\d{5})/i);if(!match)return null;for(const customer of customers){const order=customer.orders.find(o=>o.id===`NS-${match[1]}`);if(order)return {order,customer};}return null;}
export function retrieve(input){const q=new Set(words(input));return articles.map(a=>({article:a,score:words(`${a.title} ${a.category} ${a.body}`).reduce((n,w)=>n+(q.has(w)?1:0),0)})).filter(x=>x.score>0).sort((a,b)=>b.score-a.score).slice(0,2).map(x=>x.article);}
const conversationalPolicies={
 'KB-101':'Standard shipping takes **3–5 business days** after dispatch; express takes **1–2 business days**. These are estimates and carrier delays can affect them. Are you checking an existing order?',
 'KB-102':'You can generally return unused items in their original packaging within **30 days of delivery**. Final-sale items aren’t eligible. Refunds take **5–10 business days** after inspection.',
 'KB-103':'We can review changes while an order is still processing. Once it’s packed or shipped, cancellation isn’t available. What’s your order number?',
 'KB-104':'A pending payment can be an authorization rather than a settled charge. Duplicate charges need a specialist’s review. Are you seeing a pending payment or two settled charges?',
 'KB-105':'Products include a **one-year limited warranty** for manufacturing defects. Accidental damage and normal wear aren’t covered. What’s happening with your product?',
 'KB-106':'You can update your email and shipping address in **Account Settings**. Access verification and data deletion need a specialist. What would you like to change?'
};
export function respond(input,history=[]){const technical=respondTechnical(input,history);if(technical)return technical;const prior=[...history];if(prior.at(-1)?.role==='user'&&prior.at(-1).content===input)prior.pop();
  const previousUser=[...prior].reverse().find(m=>m.role==='user')?.content||'';
  if(/^(hi|hello|hey|good morning|good afternoon)[!. ]*$/i.test(input.trim()))return {reply:'Hi! I’m here to help with orders, returns, or technical issues. What can I help you with today?',sources:[],escalate:false};
  if(/^(thanks|thank you|thank you so much|great|awesome)[!. ]*$/i.test(input.trim()))return {reply:'You’re welcome! Is there anything else you’d like help with?',sources:[],escalate:false};
  const found=lookupOrder(input), lastOrder=[...history].reverse().find(m=>m.orderId)?.orderId;const contextOrder=found||((/\b(it|my order|the order|cancel|return)\b/i.test(input)&&lastOrder)?lookupOrder(lastOrder):null);const intent=found&&/^NS[- ]?\d{5}[!. ]*$/i.test(input.trim())?previousUser:input;const sources=[];let reply='',escalate=false;
  if(/(human|person|agent|representative|complaint|fraud|stolen|dispute|duplicate charge|charged twice|delete my data|can't access|cannot access)/i.test(input)){escalate=true;reply="I can help you get this ready for a specialist. Select **Create handoff** below, and I’ll include our conversation so you won’t need to explain it again. This creates a demo ticket; it doesn’t contact a real support team.";return {reply,sources,escalate};}
  else if(contextOrder){const {order}=contextOrder;if(/cancel|change|edit/i.test(intent)){sources.push('KB-103');reply=order.status==='Processing'?`Order **${order.id}** is still processing. Changes or cancellations may be possible before fulfillment, but I can't make that change here. I can prepare a human handoff so a specialist can review it.`:`Order **${order.id}** is **${order.status.toLowerCase()}**, so it can no longer be canceled. If eligible, you can request a return after delivery.`;if(order.status==='Processing')escalate=true;}else if(/return|refund/i.test(intent)){sources.push('KB-102');reply=`Order **${order.id}** is **${order.status.toLowerCase()}**. Unused items in original packaging can generally be returned within 30 days of delivery. Refunds typically reach the original payment method 5–10 business days after inspection. I can connect you with a specialist to start the request.`;escalate=true;}else{reply=`I found **${order.id}** for ${contextOrder.customer.name}: **${order.product}** is **${order.status.toLowerCase()}**. ${order.status==='Processing'?'Estimated delivery:':order.status==='Delivered'?'Delivered:':'Estimated delivery:'} **${order.eta}**.${order.tracking.startsWith('Not')?' Tracking is not available until dispatch.':` Tracking reference: **${order.tracking}**.`}`;}return {reply,sources,orderId:order.id,escalate};}
  if(/\b(order|tracking|package|shipment|delivery status)\b/i.test(input)&&!/shipping|delivery time|long|policy/i.test(input))return {reply:'Let’s check that. What’s your order number? You can try **NS-20481** from the sample orders in this demo.',sources:[],escalate:false};
  const hits=retrieve(input);if(hits.length){const a=hits[0];sources.push(a.id);reply=conversationalPolicies[a.id]||a.body; if(/return|refund/i.test(input))reply+=' What’s the order number for the item you’d like to return?';}else reply="I’m not sure yet, and I don’t want to guess. Is this about an order, a return, billing, or a technical issue?";
  return {reply,sources,escalate};}
