import {articles,customers} from './data.js';
import {respondTechnical} from './technical.js';
const words=s=>(s.toLowerCase().match(/[a-z]{3,}/g)||[]).filter(w=>!['what','with','this','that','your','have','from','would','about','please','there','order'].includes(w));
export function lookupOrder(input){const match=input.match(/NS[- ]?(\d{5})/i);if(!match)return null;for(const customer of customers){const order=customer.orders.find(o=>o.id===`NS-${match[1]}`);if(order)return {order,customer};}return null;}
export function retrieve(input){const q=new Set(words(input));return articles.map(a=>({article:a,score:words(`${a.title} ${a.category} ${a.body}`).reduce((n,w)=>n+(q.has(w)?1:0),0)})).filter(x=>x.score>0).sort((a,b)=>b.score-a.score).slice(0,2).map(x=>x.article);}
export function respond(input,history=[]){const technical=respondTechnical(input,history);if(technical)return technical;const lower=input.toLowerCase(), found=lookupOrder(input), lastOrder=[...history].reverse().find(m=>m.orderId)?.orderId;const contextOrder=found||((/\b(it|my order|the order|cancel|return)\b/i.test(input)&&lastOrder)?lookupOrder(lastOrder):null);const sources=[];let reply='',escalate=false;
  if(/(human|person|agent|representative|complaint|fraud|stolen|dispute|duplicate charge|charged twice|delete my data|can't access|cannot access)/i.test(input)){escalate=true;reply="I understand. This needs a human specialist, so I've prepared a handoff with our conversation and the relevant order details. Select **Create handoff** below to generate a demo support ticket. This demo won't send it to a real team.";return {reply,sources,escalate};}
  else if(contextOrder){const {order}=contextOrder;if(/cancel|change|edit/i.test(input)){sources.push('KB-103');reply=order.status==='Processing'?`Order **${order.id}** is still processing. Changes or cancellations may be possible before fulfillment, but I can't make that change here. I can prepare a human handoff so a specialist can review it.`:`Order **${order.id}** is **${order.status.toLowerCase()}**, so it can no longer be canceled. If eligible, you can request a return after delivery.`;if(order.status==='Processing')escalate=true;}else if(/return|refund/i.test(input)){sources.push('KB-102');reply=`Order **${order.id}** is **${order.status.toLowerCase()}**. Unused items in original packaging can generally be returned within 30 days of delivery. Refunds typically reach the original payment method 5–10 business days after inspection. I can connect you with a specialist to start the request.`;escalate=true;}else{reply=`I found **${order.id}** for ${contextOrder.customer.name}: **${order.product}** is **${order.status.toLowerCase()}**. ${order.status==='Processing'?'Estimated delivery:':order.status==='Delivered'?'Delivered:':'Estimated delivery:'} **${order.eta}**.${order.tracking.startsWith('Not')?' Tracking is not available until dispatch.':` Tracking reference: **${order.tracking}**.`}`;}return {reply,sources,orderId:order.id,escalate};}
  if(/\b(order|tracking|package|shipment|delivery status)\b/i.test(input)&&!/shipping|delivery time|long|policy/i.test(input))return {reply:'I can look up an order if you share its order number (for example, **NS-20481**). I only have access to the sample orders in this demo.',sources:[],escalate:false};
  const hits=retrieve(input);if(hits.length){const a=hits[0];sources.push(a.id);reply=a.body; if(/return|refund/i.test(input))reply+=' If you want help starting a return, share an order number.';}else reply="I don't have a reliable answer in the demo knowledge base. You can ask about shipping, returns, cancellations, billing, warranty, or an order number such as **NS-20481**. For anything else, I can connect you with a specialist.";
  return {reply,sources,escalate};}
