import './style.css';
import {articles,customers,scenarios} from './data.js';
import {respond,lookupOrder} from './agent.js';
import {ticketStatuses,ticketPriorities,ticketAssignees,createTicket,updateTicket,addTicketNote,filterTickets,loadTickets,saveTickets,sampleTicket} from './tickets.js';
let ticketStorage;try{ticketStorage=window.localStorage;}catch{}
let tickets=loadTickets(ticketStorage),selectedTicketId=null,storageWarning=false,inboxFilters={query:'',status:'All',priority:'All'};
const $=s=>document.querySelector(s);
const icon={spark:'✦',grid:'▦',chat:'◉',book:'▤',people:'♧',settings:'⚙',arrow:'↗',send:'➤',search:'⌕',close:'×'};
let messages=[],activeCustomer=customers[0],mode='demo',ticket=null,tab='chat',busy=false,viewMode='customer',customerArticle=null;
const initial={role:'assistant',content:"Hi, I'm Nova, your Northstar support assistant. I can help with orders, shipping, returns, technical troubleshooting, and product questions. What can I help you with today?",time:clock(),sources:[]};
function clock(){return new Date().toLocaleTimeString([],{hour:'numeric',minute:'2-digit'});}function escape(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}function format(s){return escape(s).replace(/\*\*(.*?)\*\*/g,'<strong>$1</strong>').replace(/\n/g,'<br>');}
function avatar(name){return name.split(' ').map(x=>x[0]).join('').slice(0,2).toUpperCase();}
function viewSwitcher(){return `<div class="view-switcher" aria-label="Demo perspective"><button id="switch-customer" aria-pressed="${viewMode==='customer'}" class="${viewMode==='customer'?'active':''}">Customer View</button><button id="switch-agent" aria-pressed="${viewMode==='agent'}" class="${viewMode==='agent'?'active':''}">Agent View</button></div>`;}
function render(){if(viewMode==='customer'){$('#app').innerHTML=customerView();bind();return;} $('#app').innerHTML=`<div class="shell"><aside class="sidebar"><div class="brand"><div class="brandmark">✳</div><div><strong>northstar</strong><small>SUPPORT STUDIO</small></div></div><div class="workspace-label">WORKSPACE <span>⌄</span></div><nav><button class="navitem ${tab==='chat'?'selected':''}" data-tab="chat"><span>${icon.chat}</span> Playground <i>01</i></button><button class="navitem ${tab==='inbox'?'selected':''}" data-tab="inbox" aria-label="Agent Inbox"><span>▣</span> Agent Inbox <i>${tickets.filter(t=>t.status!=='Resolved').length}</i></button><button class="navitem ${tab==='knowledge'?'selected':''}" data-tab="knowledge"><span>${icon.book}</span> Knowledge base</button><button class="navitem ${tab==='customers'?'selected':''}" data-tab="customers"><span>${icon.people}</span> Customers</button></nav><div class="side-bottom"><div class="mini-heading">PROJECT STATUS</div><div class="status-card"><div class="live-line"><span class="pulse"></span> Demo environment</div><p>Ready to explore with sample data</p><div class="progress"><span></span></div><div class="status-footer"><span>Agent online</span><span>●</span></div></div><a class="side-link" href="https://github.com/new" target="_blank" rel="noreferrer">${icon.arrow} Publish to GitHub</a><div class="profile"><div class="profile-avatar">JS</div><div><strong>Portfolio workspace</strong><small>Agent View · Demo</small></div><span>⌄</span></div></div></aside><main class="main"><header class="topbar"><div class="breadcrumbs">Workspace <span>/</span> <b>${tab==='chat'?'AI Playground':tab==='knowledge'?'Knowledge base':tab==='inbox'?'Agent Inbox':'Customers'}</b></div><div class="top-actions">${viewSwitcher()}<select class="mobile-navigation" id="mobile-navigation" aria-label="Workspace navigation">${[['chat','Playground'],['inbox','Agent Inbox'],['knowledge','Knowledge base'],['customers','Customers']].map(([value,label])=>`<option value="${value}" ${tab===value?'selected':''}>${label}</option>`).join('')}</select><span class="top-live"><span class="pulse"></span> System operational</span><span class="top-avatar">JS</span></div></header><div class="page">${tab==='chat'?chatView():tab==='knowledge'?knowledgeView():tab==='inbox'?inboxView():customersView()}</div></main></div>`;bind();}
function customerView(){
 const ownTickets=tickets.filter(t=>t.customer.id===activeCustomer.id);
 return `<div class="customer-shell"><header class="customer-header"><div class="brand"><div class="brandmark">✳</div><div><strong>northstar</strong><small>CUSTOMER SUPPORT</small></div></div>${viewSwitcher()}</header><main class="customer-page"><div class="customer-intro"><div class="eyebrow"><span class="eyebrow-dot"></span> CUSTOMER EXPERIENCE · DEMO V 1.3</div><h1>How can we help?</h1><p>Chat with Nova for order questions, troubleshooting, or help from a support specialist.</p><div class="customer-demo-note">You're exploring as ${escape(activeCustomer.name)}, a fictional customer. The view switch is a portfolio demonstration.</div></div><div class="customer-layout"><div class="customer-chat-column"><div class="customer-chat-tools"><span><span class="pulse"></span> Nova is ready to help</span><button class="outline-btn" id="reset">↻ New conversation</button></div>${chatPanelView()}${customerArticle?`<section class="customer-source info-card"><div class="card-title"><span>${escape(customerArticle.id)} · SUPPORT ARTICLE</span><button class="outline-btn" id="close-customer-article" aria-label="Close article">×</button></div><h2>${escape(customerArticle.title)}</h2><p>${escape(customerArticle.body)}</p></section>`:''}<div class="customer-quick-actions">${scenarios.map((scenario,i)=>`<button class="outline-btn" data-scenario="${i}">${escape(scenario.title)}</button>`).join('')}</div></div><aside class="customer-support-column"><section class="info-card"><div class="card-title"><span>YOUR ORDERS</span><span class="subtle">SAMPLE DATA</span></div>${activeCustomer.orders.map(o=>`<button class="order-row" data-order="${o.id}"><span class="order-icon">▣</span><span><strong>${escape(o.id)}</strong><small>${escape(o.product)}</small></span><span class="order-status ${o.status==='Delivered'?'delivered':''}">${escape(o.status)}</span></button>`).join('')}<p class="card-foot">Choose an order to ask Nova for an update.</p></section><section class="info-card"><div class="card-title"><span>YOUR SUPPORT REQUESTS</span></div>${ownTickets.length?ownTickets.map(t=>`<div class="customer-request"><div><strong>${escape(t.id)}</strong>${ticketBadge(t.status)}</div><p>${escape(t.subject)}</p><small>Created ${escape(dateLabel(t.createdAt))}</small></div>`).join(''):'<p class="customer-help-copy">When you request a human handoff, your ticket confirmation and status will appear here.</p>'}</section><section class="customer-help-card"><span>✧</span><h2>Help that keeps the context</h2><p>If Nova cannot resolve your issue, your conversation and troubleshooting steps travel with your support request.</p></section></aside></div><footer class="customer-footer">Fictional data · Demo responses · No real agent is contacted. Switch to Agent View to explore the support team's workflow.</footer></main></div>`;
}
function chatView(){return `<div class="page-heading"><div><div class="eyebrow"><span class="eyebrow-dot"></span> INTERACTIVE DEMO <span class="eyebrow-line"></span> V 1.3</div><h1>AI Support Playground<span class="heading-star">✳</span></h1><p>See how an AI agent handles real support conversations, from first question to resolution.</p></div><button class="outline-btn" id="reset">↻ &nbsp; New conversation</button></div><div class="metrics"><div class="metric"><span class="metric-icon violet">✦</span><span class="metric-label">AGENT STATUS</span><strong>Online <span class="green-dot">●</span></strong><small>Ready to assist</small></div><div class="metric"><span class="metric-icon blue">▤</span><span class="metric-label">KNOWLEDGE ARTICLES</span><strong>${articles.length} articles</strong><small>Grounded responses</small></div><div class="metric"><span class="metric-icon peach">♧</span><span class="metric-label">SAMPLE CUSTOMERS</span><strong>${customers.length} profiles</strong><small>With order history</small></div><div class="metric"><span class="metric-icon mint">↗</span><span class="metric-label">ESCALATION</span><strong>Human handoff</strong><small>Context preserved</small></div></div><div class="content-grid">${chatPanelView()}<aside class="context-column"><div class="info-card"><div class="card-title"><span>◎ &nbsp; CUSTOMER CONTEXT</span><span class="subtle">DEMO DATA</span></div><label for="customer-select">Active customer</label><select id="customer-select">${customers.map(c=>`<option value="${c.id}" ${activeCustomer.id===c.id?'selected':''}>${escape(c.name)} · ${c.id}</option>`).join('')}</select><div class="customer-row"><div class="customer-avatar">${avatar(activeCustomer.name)}</div><div><strong>${escape(activeCustomer.name)}</strong><small>${escape(activeCustomer.email)}</small></div><span class="tier">${activeCustomer.tier}</span></div><div class="divider"></div><div class="mini-heading">RECENT ORDERS</div>${activeCustomer.orders.map(o=>`<button class="order-row" data-order="${o.id}"><span class="order-icon">▣</span><span><strong>${o.id}</strong><small>${escape(o.product)}</small></span><span class="order-status ${o.status==='Delivered'?'delivered':''}">${o.status}</span></button>`).join('')}<p class="card-foot">Click an order to ask Nova about it.</p></div><div class="info-card scenario-card"><div class="card-title"><span>✧ &nbsp; TRY A SCENARIO</span></div><p>See the agent in action with these common support requests.</p>${scenarios.map((s,i)=>`<button class="scenario" data-scenario="${i}"><span class="scenario-icon">${['⚙','◫','↶','⊘','♧'][i]}</span><span><strong>${s.title}</strong><small>${s.description}</small></span><span class="scenario-arrow">↗</span></button>`).join('')}</div></aside></div><div class="bottom-caption"><span>✳</span> Built to demonstrate grounded answers, technical troubleshooting, order context, and human escalation. <span class="caption-right">PORTFOLIO PROJECT · 2026</span></div></div>`;}
function chatPanelView(){return `<section class="chat-panel"><div class="panel-header"><div class="agent-avatar">✳</div><div><strong>Nova <span class="ai-badge">AI AGENT</span></strong><small><span class="green-dot">●</span> Online · Typically replies instantly</small></div><div class="panel-menu">•••</div></div><div class="chat-body" id="chat-body">${(messages.length?messages:[initial]).map(messageView).join('')}${busy?`<div class="message assistant"><div class="message-avatar">✳</div><div class="bubble typing"><span></span><span></span><span></span></div></div>`:''}</div><div class="chat-bottom">${ticket?`<div class="ticket-note">✓ Demo handoff ${escape(ticket.id)} created · ${viewMode==='agent'?'<button id="view-ticket">Open in Agent Inbox ↗</button>':'<span>Request received</span>'}</div>`:''}<div class="composer"><textarea id="message-input" rows="1" maxlength="2000" placeholder="Ask a question or enter an order number..." aria-label="Message Nova"></textarea><button id="send" aria-label="Send message" ${busy?'disabled':''}>${icon.send}</button></div><div class="composer-foot"><span>✦ &nbsp; ${mode==='ai'?'AI responses enabled':'Demo responses active'} · Sample data only</span><span>Press Enter to send</span></div></div></section>`;}
function messageView(m){return `<div class="message ${m.role}">${m.role==='assistant'?'<div class="message-avatar">✳</div>':''}<div class="message-stack"><div class="bubble">${format(m.content)}</div>${m.sources?.length?`<div class="sources">${m.sources.map(id=>`<button class="source" data-source="${id}">▤ ${id} · View source ↗</button>`).join('')}</div>`:''}${m.escalate&&!ticket&&m===messages.at(-1)?'<button class="handoff" id="handoff">↗ &nbsp; Create handoff <span>Human specialist</span></button>':''}<small class="timestamp">${m.role==='assistant'?'Nova · ':''}${m.time}</small></div></div>`;}
function knowledgeView(){return `<div class="page-heading"><div><div class="eyebrow"><span class="eyebrow-dot"></span> VERIFIED CONTENT</div><h1>Knowledge base<span class="heading-star">✳</span></h1><p>Clear, source-backed guidance used by Nova to answer customer questions.</p></div></div><div class="knowledge-grid">${articles.map(a=>`<article class="article-card" id="${a.id}"><div class="article-top"><span class="article-icon">▤</span><span>${a.id}</span></div><div class="category">${a.category}</div><h2>${a.title}</h2><p>${a.body}</p><button data-ask="${a.title}">Ask Nova about this ↗</button></article>`).join('')}</div><div class="data-disclaimer">All policies and customer data are fictional and provided for portfolio demonstration.</div>`;}
function customersView(){return `<div class="page-heading"><div><div class="eyebrow"><span class="eyebrow-dot"></span> SIMULATED CRM</div><h1>Customer records<span class="heading-star">✳</span></h1><p>Explore the fictional customer and order records used in the support demo.</p></div></div><div class="customers-grid">${customers.map(c=>`<article class="record-card"><div class="record-person"><div class="customer-avatar">${avatar(c.name)}</div><div><h2>${c.name}</h2><span>${c.email}</span></div><span class="tier">${c.tier}</span></div><div class="record-id">CUSTOMER ID <strong>${c.id}</strong></div><div class="mini-heading">ORDER HISTORY</div>${c.orders.map(o=>`<div class="record-order"><div><strong>${o.id}</strong><span>${o.product}</span><small>Placed ${o.date} · ${o.total}</small></div><span class="order-status ${o.status==='Delivered'?'delivered':''}">${o.status}</span></div>`).join('')}<button class="record-button" data-customer="${c.id}">Open in playground ↗</button></article>`).join('')}</div><div class="data-disclaimer">These records are synthetic. No real customer information is stored or accessed.</div>`;}
function bind(){bindInbox();$('#switch-customer')?.addEventListener('click',()=>{viewMode='customer';customerArticle=null;render();scroll()});$('#switch-agent')?.addEventListener('click',()=>{viewMode='agent';tab='inbox';render()});$('#close-customer-article')?.addEventListener('click',()=>{customerArticle=null;render()});$('#mobile-navigation')?.addEventListener('change',e=>{tab=e.target.value;render()});document.querySelectorAll('[data-tab]').forEach(el=>el.onclick=()=>{tab=el.dataset.tab;render()});$('#reset')?.addEventListener('click',()=>{messages=[];ticket=null;render()});$('#customer-select')?.addEventListener('change',e=>{activeCustomer=customers.find(c=>c.id===e.target.value);messages=[];ticket=null;render()});document.querySelectorAll('[data-order]').forEach(el=>el.onclick=()=>send(`Where is my order ${el.dataset.order}?`));document.querySelectorAll('[data-scenario]').forEach(el=>el.onclick=()=>send(scenarios[+el.dataset.scenario].prompt.replace(/NS-\d{5}/g,activeCustomer.orders[0].id)));document.querySelectorAll('[data-ask]').forEach(el=>el.onclick=()=>{tab='chat';render();send(`Tell me about ${el.dataset.ask}`)});document.querySelectorAll('[data-customer]').forEach(el=>el.onclick=()=>{activeCustomer=customers.find(c=>c.id===el.dataset.customer);messages=[];ticket=null;viewMode='customer';tab='chat';render()});document.querySelectorAll('[data-source]').forEach(el=>el.onclick=()=>{if(viewMode==='customer'){customerArticle=articles.find(a=>a.id===el.dataset.source);render();}else{tab='knowledge';render();document.getElementById(el.dataset.source)?.scrollIntoView({behavior:'smooth',block:'center'});}});$('#handoff')?.addEventListener('click',handoff);$('#send')?.addEventListener('click',()=>send($('#message-input').value));$('#message-input')?.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send(e.target.value)}});}
async function send(value){const input=value?.trim();if(!input||busy)return;if(ticket)ticket=null;tab='chat';messages.push({role:'user',content:input,time:clock()});busy=true;render();scroll();const history=messages.map(m=>({role:m.role,content:m.content,orderId:m.orderId}));let result;try{const response=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({messages:history.map(({role,content})=>({role,content}))})});if(!response.ok)throw new Error('Demo mode');result=await response.json();mode=result.mode==='demo'?'demo':'ai';}catch{result=respond(input,history);mode='demo';await new Promise(resolve=>setTimeout(resolve,450));}messages.push({role:'assistant',content:result.reply,sources:result.sources||[],orderId:result.orderId,escalate:result.escalate,technical:result.technical,time:clock()});busy=false;render();scroll();}
function scroll(){const el=$('#chat-body');if(el)el.scrollTop=el.scrollHeight;}
function handoff(){
  if(ticket||busy)return;
  const related=[...messages].reverse().find(m=>m.orderId)?.orderId;
  const owner=related?lookupOrder(related)?.customer:activeCustomer;
  ticket=createTicket({messages,customer:owner||activeCustomer});
  tickets.unshift(ticket);selectedTicketId=ticket.id;persistTickets();
  messages.push({role:'assistant',content:`Your demo support request **${ticket.id}** has been created.\n\n**Issue:** ${ticket.summary}\n\nThe customer details, conversation, and troubleshooting history have been preserved. A support specialist can review the issue and the steps you tried. No real agent has been notified.`,time:clock(),sources:[]});
  render();scroll();
}
function dateLabel(value){const d=new Date(value);return Number.isNaN(d.getTime())?'Unknown date':d.toLocaleString([],{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'});}
function persistTickets(){storageWarning=!saveTickets(ticketStorage,tickets);}
function ticketBadge(status){return `<span class="ticket-status ${status==='Resolved'?'resolved':status==='In progress'?'in-progress':'open'}">${escape(status)}</span>`;}
function options(values,selected){return values.map(v=>`<option value="${escape(v)}" ${v===selected?'selected':''}>${escape(v)}</option>`).join('');}
function inboxView(){
 const visible=filterTickets(tickets,inboxFilters);
 const selected=tickets.find(t=>t.id===selectedTicketId);
 return `<div class="page-heading"><div><div class="eyebrow"><span class="eyebrow-dot"></span> HUMAN SUPPORT · DEMO WORKSPACE</div><h1>Agent Inbox<span class="heading-star">✳</span></h1><p>Pick up where Nova left off. Review context, manage the case, and record the outcome.</p></div><button class="outline-btn" id="sample-ticket">＋ Add sample ticket</button></div>
 <div class="inbox-notice">Demo tickets stay in this browser. No real agent is notified. Use fictional information only.${storageWarning?' <strong>Browser storage is unavailable; changes will last only until this page closes.</strong>':''}</div>
 <div class="metrics">${[['TOTAL TICKETS',tickets.length,'blue'],['OPEN',tickets.filter(t=>t.status==='Open').length,'violet'],['IN PROGRESS',tickets.filter(t=>t.status==='In progress').length,'peach'],['RESOLVED',tickets.filter(t=>t.status==='Resolved').length,'mint']].map(([label,count,color])=>`<div class="metric"><span class="metric-icon ${color}">▣</span><span class="metric-label">${label}</span><strong>${count}</strong><small>Current browser workspace</small></div>`).join('')}</div>
 <div class="inbox-grid"><section class="inbox-list info-card"><div class="card-title"><span>TICKET QUEUE</span><span class="subtle">${visible.length} SHOWN</span></div><div class="ticket-filters"><label for="ticket-search">Search tickets</label><input id="ticket-search" type="search" placeholder="Issue, customer, or ticket ID" value="${escape(inboxFilters.query)}"><div class="filter-pair"><div><label for="ticket-status-filter">Status</label><select id="ticket-status-filter">${options(['All',...ticketStatuses],inboxFilters.status)}</select></div><div><label for="ticket-priority-filter">Priority</label><select id="ticket-priority-filter">${options(['All',...ticketPriorities],inboxFilters.priority)}</select></div></div></div><div class="ticket-rows">${visible.length?visible.map(t=>`<button class="ticket-row ${selectedTicketId===t.id?'active':''}" data-ticket="${escape(t.id)}" aria-pressed="${selectedTicketId===t.id}"><div class="ticket-row-top"><span>${escape(t.id)}</span>${ticketBadge(t.status)}</div><strong>${escape(t.subject)}</strong><div class="ticket-row-meta"><span>${escape(t.customer.name)}</span><span class="priority ${t.priority.toLowerCase()}">${escape(t.priority)}</span></div><small>${escape(dateLabel(t.createdAt))}${t.sample?' · SAMPLE TICKET':''}</small></button>`).join(''):`<div class="inbox-empty"><span>▣</span><h2>${tickets.length?'No matching tickets':'Your queue is clear'}</h2><p>${tickets.length?'Adjust the search or filters to see more tickets.':'Create a handoff in the Playground, or add a sample ticket to explore the workflow.'}</p>${tickets.length?'<button class="outline-btn" id="clear-filters">Clear filters</button>':'<button class="outline-btn" data-tab="chat">Open Playground ↗</button>'}</div>`}</div></section>
 <section class="ticket-detail info-card">${selected?ticketDetail(selected):'<div class="inbox-empty detail-empty"><span>↗</span><h2>Select a ticket</h2><p>Customer context, conversation history, and case controls will appear here.</p></div>'}</section></div>`;
}
function ticketDetail(t){return `<div class="ticket-detail-heading"><div class="eyebrow">${escape(t.id)}${t.sample?' · SAMPLE TICKET':''}</div>${ticketBadge(t.status)}<h2>${escape(t.subject)}</h2><p>Created ${escape(dateLabel(t.createdAt))} · ${escape(t.category)}</p></div>
 <div class="ticket-controls">${[['status','Status',ticketStatuses],['priority','Priority',ticketPriorities],['assignee','Assigned to',ticketAssignees]].map(([field,label,values])=>`<div><label for="ticket-${field}">${label}</label><select id="ticket-${field}" data-ticket-field="${field}">${options(values,t[field])}</select></div>`).join('')}</div>
 <div class="ticket-customer"><div class="customer-avatar">${escape(avatar(t.customer.name))}</div><div><strong>${escape(t.customer.name)}</strong><small>${escape(t.customer.email)} · ${escape(t.customer.id)}</small></div>${t.orderId?`<span class="source">Order ${escape(t.orderId)}</span>`:''}</div>
 <div class="ticket-section"><h3>Handoff summary</h3><p>${format(t.summary)}</p></div>
 <div class="ticket-section"><h3>Troubleshooting attempted</h3>${t.attempts.length?`<ol class="ticket-checks">${t.attempts.map(a=>`<li><strong>${escape(a.step)}</strong><p>Customer result: ${escape(a.customerReply)}</p></li>`).join('')}</ol>`:'<p>No completed technical checks were recorded before this handoff.</p>'}</div>
 <details class="ticket-section transcript-section"><summary>Conversation history <span>${t.transcript.length} messages</span></summary><div class="ticket-transcript">${t.transcript.map(m=>`<div class="transcript-message ${m.role==='user'?'customer':'agent'}"><small>${m.role==='user'?'Customer':'Nova'}${m.time?' · '+escape(m.time):''}</small><p>${format(m.content)}</p></div>`).join('')}</div></details>
 <div class="ticket-section"><h3>Internal notes</h3>${t.notes.map(n=>`<div class="internal-note"><small>${escape(n.author)} · ${escape(dateLabel(n.at))}</small><p>${format(n.text)}</p></div>`).join('')}<form id="ticket-note-form"><label for="ticket-note">Add a note for the next agent</label><textarea id="ticket-note" maxlength="2000" placeholder="Record next steps or how the issue was resolved." required></textarea><button class="primary-btn" type="submit">Save note</button></form></div>
 <details class="ticket-section activity-section"><summary>Activity log <span>${t.activity.length} events</span></summary><ul>${[...t.activity].reverse().map(a=>`<li><span>${escape(a.text)}</span><small>${escape(dateLabel(a.at))}</small></li>`).join('')}</ul></details>`;}
function bindInbox(){
 document.querySelectorAll('[data-ticket]').forEach(el=>el.onclick=()=>{selectedTicketId=el.dataset.ticket;render()});
 $('#sample-ticket')?.addEventListener('click',()=>{const sample=sampleTicket(customers[1]);tickets.unshift(sample);selectedTicketId=sample.id;inboxFilters={query:'',status:'All',priority:'All'};persistTickets();render()});
 $('#ticket-search')?.addEventListener('input',e=>{const value=e.target.value;inboxFilters.query=value;render();const input=$('#ticket-search');input.focus();});
 for(const field of ['status','priority'])$('#ticket-'+field+'-filter')?.addEventListener('change',e=>{inboxFilters[field]=e.target.value;render()});
 $('#clear-filters')?.addEventListener('click',()=>{inboxFilters={query:'',status:'All',priority:'All'};render()});
 document.querySelectorAll('[data-ticket-field]').forEach(el=>el.onchange=()=>{tickets=tickets.map(t=>t.id===selectedTicketId?updateTicket(t,el.dataset.ticketField,el.value):t);persistTickets();render()});
 $('#ticket-note-form')?.addEventListener('submit',e=>{e.preventDefault();const note=$('#ticket-note').value;if(!note.trim())return;tickets=tickets.map(t=>t.id===selectedTicketId?addTicketNote(t,note):t);persistTickets();render()});
 $('#view-ticket')?.addEventListener('click',()=>{selectedTicketId=ticket.id;tab='inbox';inboxFilters={query:'',status:'All',priority:'All'};render()});
}

render();
