export const articles = [
  {id:'KB-101',category:'Shipping',title:'Shipping & delivery',body:'Standard delivery takes 3–5 business days after dispatch. Express delivery takes 1–2 business days. Tracking becomes available when the carrier scans your package. Delivery estimates can change due to carrier delays.'},
  {id:'KB-102',category:'Returns',title:'Returns & exchanges',body:'Unused items in original packaging can be returned within 30 days of delivery. Start a return with your order number. Refunds go to the original payment method within 5–10 business days after inspection. Final-sale items are not eligible.'},
  {id:'KB-103',category:'Orders',title:'Change or cancel an order',body:'Orders can be edited or canceled before they enter fulfillment. Once an order is packed or shipped, cancellation is unavailable; an eligible item can be returned after delivery.'},
  {id:'KB-104',category:'Payments',title:'Billing & payment issues',body:'We accept major credit cards and digital wallets. A pending authorization can appear before a charge settles. For duplicate charges or payment disputes, a human specialist must review the account.'},
  {id:'KB-105',category:'Warranty',title:'Product warranty',body:'Northstar products include a one-year limited warranty against manufacturing defects. Accidental damage and normal wear are excluded. A support specialist can review photos and proof of purchase.'},
  {id:'KB-106',category:'Account',title:'Account & privacy',body:'Customers can update their email and shipping addresses in Account Settings. For account access, identity verification, personal data deletion, or suspected fraud, connect with a human specialist.'},
  {id:'KB-107',category:'Technical Support',title:'Device connectivity',body:'For Bluetooth accessories, check power, charge, Bluetooth availability, and proximity. Restart the accessory, toggle Bluetooth, and reopen its companion app. Remove and re-pair only the affected accessory using manufacturer instructions; check whether it is connected elsewhere. Escalate after these checks fail. Never factory-reset as a routine first step.'},
  {id:'KB-108',category:'Technical Support',title:'Login troubleshooting',body:'Check the intended account email and the sign-in error. Try the official sign-in page in a private window or another browser. Use the official Forgot password flow for rejected passwords and check spam for a reset email. Never request passwords, recovery codes, or verification codes in chat. Lockouts, missing verification codes, and identity verification require a human specialist.'},
  {id:'KB-109',category:'Technical Support',title:'App and error troubleshooting',body:'Save work before restarting an app or refreshing a page. Collect the app name, error code, device or browser, and triggering action without personal information. Check connectivity, try a private window or another browser, and apply official app updates. Avoid clearing app data, reinstalling, or factory resets without official instructions and a backup. Escalate persistent errors with the checks attempted.'}
];
export const customers = [
  {id:'C-1042',name:'Alex Morgan',email:'alex.morgan@example.com',tier:'Plus',orders:[{id:'NS-20481',product:'Everyday Carry Backpack',date:'Sep 24, 2026',status:'In transit',eta:'Oct 2, 2026',tracking:'1Z-DEMO-20481',total:'$129.00'},{id:'NS-19876',product:'Insulated Travel Bottle',date:'Aug 18, 2026',status:'Delivered',eta:'Aug 23, 2026',tracking:'1Z-DEMO-19876',total:'$38.00'}]},
  {id:'C-2087',name:'Taylor Reed',email:'taylor.reed@example.com',tier:'Standard',orders:[{id:'NS-20512',product:'Desk Essentials Kit',date:'Sep 27, 2026',status:'Processing',eta:'Oct 5, 2026',tracking:'Not available yet',total:'$84.00'},{id:'NS-19104',product:'Wireless Charging Pad',date:'Jul 10, 2026',status:'Delivered',eta:'Jul 15, 2026',tracking:'1Z-DEMO-19104',total:'$59.00'}]},
  {id:'C-3321',name:'Jordan Lee',email:'jordan.lee@example.com',tier:'Plus',orders:[{id:'NS-20319',product:'Commuter Tech Organizer',date:'Sep 20, 2026',status:'Delivered',eta:'Sep 26, 2026',tracking:'1Z-DEMO-20319',total:'$46.00'}]}
];
export const scenarios=[{title:'Technical support',description:'Troubleshoot a device or app issue',prompt:'I need technical support. My device won’t connect.'},{title:'Where is my order?',description:'Check a live-like order record',prompt:'Where is my order NS-20481?'},{title:'Can I return this?',description:'Find the return policy',prompt:'What is your return policy?'},{title:'Cancel my order',description:'Test a fulfillment constraint',prompt:'Can I cancel order NS-20512?'},{title:'Talk to a person',description:'See the escalation handoff',prompt:'I need to talk to a human about a duplicate charge.'}];
